// Created by TraceCompiler 2.2.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CCONTENTINFOTRACES_H__
#define __CCONTENTINFOTRACES_H__

#define KOstTraceComponentID 0x2001f6fb

#define CCONTENTINFO_NEWL_ENTRY 0x8a0017
#define CCONTENTINFO_NEWL_EXIT 0x8a0018
#define CCONTENTINFO_NEWLC_ENTRY 0x8a0019
#define CCONTENTINFO_NEWLC_EXIT 0x8a001a
#define CCONTENTINFO_GETNAMEL_ENTRY 0x8a001b
#define CCONTENTINFO_GETNAMEL_EXIT 0x8a001c
#define CCONTENTINFO_SETNAMEL_ENTRY 0x8a001d
#define CCONTENTINFO_SETNAMEL_EXIT 0x8a001e


#endif

// End of file

