// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CONTENTINFOMGRTRACES_H__
#define __CONTENTINFOMGRTRACES_H__

#define KOstTraceComponentID 0x2001f6fb

#define CCONTENTINFOMGR_NEWL_ENTRY 0x8a0035
#define CCONTENTINFOMGR_NEWL_EXIT 0x8a0036
#define CCONTENTINFOMGR_NEWLC_ENTRY 0x8a0037
#define CCONTENTINFOMGR_NEWLC_EXIT 0x8a0038
#define CCONTENTINFOMGR_CONSTRUCTL_ENTRY 0x8a0039
#define CCONTENTINFOMGR_CONSTRUCTL_EXIT 0x8a003a


#endif

// End of file

