// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CCPIXSEARCHERTRACES_H__
#define __CCPIXSEARCHERTRACES_H__

#define KOstTraceComponentID 0x2001f6fe

#define CCPIXSEARCHER_SEARCHL_ENTRY 0x8a0001
#define DUP1_CCPIXSEARCHER_SEARCHL_ENTRY 0x8a0002
#define CCPIXSEARCHER_SEARCHL_EXIT 0x8a0003
#define CCPIXSEARCHER_GETDOCUMENTL_ENTRY 0x8a0004
#define DUP1_CCPIXSEARCHER_GETDOCUMENTL_ENTRY 0x8a0005
#define CCPIXSEARCHER_GETDOCUMENTL_EXIT 0x8a0006


#endif

// End of file

